/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as RecapRouteImport } from './routes/recap'
import { Route as ProjectionRouteImport } from './routes/projection'
import { Route as DjRouteImport } from './routes/dj'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AudienceRouteImport } from './routes/audience'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSpotifyLoginRouteImport } from './routes/api.spotify.login'
import { Route as ApiSpotifyCallbackRouteImport } from './routes/api.spotify.callback'
import { Route as ApiElevenlabsTtsRouteImport } from './routes/api.elevenlabs.tts'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapRoute = RecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionRoute = ProjectionRouteImport.update({
  id: '/projection',
  path: '/projection',
  getParentRoute: () => rootRouteImport,
} as any)
const DjRoute = DjRouteImport.update({
  id: '/dj',
  path: '/dj',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AudienceRoute = AudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyLoginRoute = ApiSpotifyLoginRouteImport.update({
  id: '/api/spotify/login',
  path: '/api/spotify/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyCallbackRoute = ApiSpotifyCallbackRouteImport.update({
  id: '/api/spotify/callback',
  path: '/api/spotify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElevenlabsTtsRoute = ApiElevenlabsTtsRouteImport.update({
  id: '/api/elevenlabs/tts',
  path: '/api/elevenlabs/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audience': typeof AudienceRoute
  '/connect': typeof ConnectRoute
  '/dj': typeof DjRoute
  '/projection': typeof ProjectionRoute
  '/recap': typeof RecapRoute
  '/sessions': typeof SessionsRoute
  '/api/elevenlabs/tts': typeof ApiElevenlabsTtsRoute
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
  '/api/spotify/login': typeof ApiSpotifyLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audience': typeof AudienceRoute
  '/connect': typeof ConnectRoute
  '/dj': typeof DjRoute
  '/projection': typeof ProjectionRoute
  '/recap': typeof RecapRoute
  '/sessions': typeof SessionsRoute
  '/api/elevenlabs/tts': typeof ApiElevenlabsTtsRoute
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
  '/api/spotify/login': typeof ApiSpotifyLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audience': typeof AudienceRoute
  '/connect': typeof ConnectRoute
  '/dj': typeof DjRoute
  '/projection': typeof ProjectionRoute
  '/recap': typeof RecapRoute
  '/sessions': typeof SessionsRoute
  '/api/elevenlabs/tts': typeof ApiElevenlabsTtsRoute
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
  '/api/spotify/login': typeof ApiSpotifyLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audience'
    | '/connect'
    | '/dj'
    | '/projection'
    | '/recap'
    | '/sessions'
    | '/api/elevenlabs/tts'
    | '/api/spotify/callback'
    | '/api/spotify/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audience'
    | '/connect'
    | '/dj'
    | '/projection'
    | '/recap'
    | '/sessions'
    | '/api/elevenlabs/tts'
    | '/api/spotify/callback'
    | '/api/spotify/login'
  id:
    | '__root__'
    | '/'
    | '/audience'
    | '/connect'
    | '/dj'
    | '/projection'
    | '/recap'
    | '/sessions'
    | '/api/elevenlabs/tts'
    | '/api/spotify/callback'
    | '/api/spotify/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudienceRoute: typeof AudienceRoute
  ConnectRoute: typeof ConnectRoute
  DjRoute: typeof DjRoute
  ProjectionRoute: typeof ProjectionRoute
  RecapRoute: typeof RecapRoute
  SessionsRoute: typeof SessionsRoute
  ApiElevenlabsTtsRoute: typeof ApiElevenlabsTtsRoute
  ApiSpotifyCallbackRoute: typeof ApiSpotifyCallbackRoute
  ApiSpotifyLoginRoute: typeof ApiSpotifyLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap': {
      id: '/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof RecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projection': {
      id: '/projection'
      path: '/projection'
      fullPath: '/projection'
      preLoaderRoute: typeof ProjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj': {
      id: '/dj'
      path: '/dj'
      fullPath: '/dj'
      preLoaderRoute: typeof DjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audience': {
      id: '/audience'
      path: '/audience'
      fullPath: '/audience'
      preLoaderRoute: typeof AudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/login': {
      id: '/api/spotify/login'
      path: '/api/spotify/login'
      fullPath: '/api/spotify/login'
      preLoaderRoute: typeof ApiSpotifyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/callback': {
      id: '/api/spotify/callback'
      path: '/api/spotify/callback'
      fullPath: '/api/spotify/callback'
      preLoaderRoute: typeof ApiSpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elevenlabs/tts': {
      id: '/api/elevenlabs/tts'
      path: '/api/elevenlabs/tts'
      fullPath: '/api/elevenlabs/tts'
      preLoaderRoute: typeof ApiElevenlabsTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudienceRoute: AudienceRoute,
  ConnectRoute: ConnectRoute,
  DjRoute: DjRoute,
  ProjectionRoute: ProjectionRoute,
  RecapRoute: RecapRoute,
  SessionsRoute: SessionsRoute,
  ApiElevenlabsTtsRoute: ApiElevenlabsTtsRoute,
  ApiSpotifyCallbackRoute: ApiSpotifyCallbackRoute,
  ApiSpotifyLoginRoute: ApiSpotifyLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
